[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = { version = "0.14.0" }
regex = { version = "1.10.4" }
clap = { version = "4.5.6", features = ["derive"] }
tokio = { version = "1.38.0", features = ["fs"] }
